#-------------------------------
# General Site Settings
title: HyunSang Park
logo: logo.svg # You can add own logo.
description: Zolan is modern minimal theme for Jekyll


#-------------------------------
# Author Settings
author:
  name: HyunSang Park
  image: 01.jpg
  say-hello: <strong>안녕하세요!</strong>
  bio: 주로 Dev-Ops와 Back-End 개발을 주로 하고 있으며,<br>다양한 분들과 함께 이야기 하는 것을 좋아합니다.


#-------------------------------
# Contact links
twitter: https://twitter.com/hyunsang_0625 # Add your Twitter handle
facebook: https://www.facebook.com/hyun.sang.0625/ # Add your Facebook handle
# dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://www.instagram.com/im_hyun.sang/ # Add your Instagram handle
# pinterest: https://pinterest.com/ # Add your Pinterest handle
github: https://github.com/Dev-HyunSang


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: artemsheludko_ # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
